//theme reducer
export const CHANGE_THEME = 'CHANGE_THEME';

//generalReducer
export const RESET_PASSWORD_MODAL = 'RESET_PASSWORD_MODAL';
export const SET_TIG_DATA = 'SET_TIG_DATA';
export const SHOW_HOW_TO_PLAY = 'SHOW_HOW_TO_PLAY';
export const SET_SHOW_SNACKBAR = 'SET_SHOW_SNACKBAR';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

//playerReducer
export const TOGGLE_MUTE_STATE = 'TOGGLE_MUTE_STATE';
export const SET_FIRST_TAP = 'SET_FIRST_TAP';
export const SET_MEDIA_INDEX = 'SET_MEDIA_INDEX';

//networkReducer
export const NETWORK_FAILURE = 'NETWORK_FAILURE';

//AUTHREDUCER
export const AUTH = 'AUTH';
export const SET_EMAIL_MOBILE = 'SET_EMAIL_MOBILE';
export const UNSET_CREDENTIALS = 'UNSET_CREDENTIALS';

//set,unset challenges in userfeed, addchallenge
export const SET_CHALLENGES = 'SET_CHALLENGES';
export const ADD_CHALLENGE_TO_FRONT = 'ADD_CHALLENGE_TO_FRONT';
export const UNSET_CHALLENGES = 'UNSET_CHALLENGES';
export const SET_NEXT_URL = 'SET_NEXT_URL';
export const SET_USER_FEED_API_CALL_COUNT = 'SET_USER_FEED_API_CALL_COUNT';
export const REMOVE_CHALLENGE = 'REMOVE_CHALLENGE';

//update/reset likes/comments
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS';
export const RESET_CHALLENGE_DETAILS = 'RESET_CHALLENGE_DETAILS';

//set,unset tigmates list
export const SET_TAG_MATES = 'SET_TAG_MATES';
export const SET_FOLLOWERS = 'SET_FOLLOWERS';
export const SET_FOLLOWING = 'SET_FOLLOWING';
export const UNSET_TAG_MATES = 'UNSET_TAG_MATES';

// set,unset userchallenges userprofile challenges
export const SET_USER_CHALLENGES = 'SET_USER_CHALLENGES';
export const UNSET_USER_CHALLENGES = 'UNSET_USER_CHALLENGES';
export const SET_PROFILE_STATS = 'SET_PROFILE_STATS';
export const SET_CHALLENGE_INFO_ID = 'SET_CHALLENGE_INFO_ID';
export const SETTING_PAGE_USER_STATS_API_CALLED = 'SETTING_PAGE_USER_STATS_API_CALLED';
export const SET_PRIVATE_ACCOUNT = 'SET_PRIVATE_ACCOUNT';
export const CHALLENGE_ADDED = 'CHALLENGE_ADDED';
export const CHALLENGE_ACCEPTED = 'CHALLENGE_ACCEPTED';
export const UNDO_CHALLENGE_ACCEPTED = 'UNDO_CHALLENGE_ACCEPTED';
export const UNDO_CHALLENGE_ADDED = 'UNDO_CHALLENGE_ADDED';
export const SET_DELETED_CHALLENGES = 'SET_DELETED_CHALLENGES';
export const CANCEL_CHALLENGE_ACCEPTED = 'CANCEL_CHALLENGE_ACCEPTED';
export const CANCEL_CHALLENGE_ADDED = 'CANCEL_CHALLENGE_ADDED';
export const REMOVE_CHALLENGE_AT_INDEX = 'REMOVE_CHALLENGE_AT_INDEX';

//set posted challenges
export const SET_POSTED_CHALLENGES = 'SET_POSTED_CHALLENGES';
export const UNSET_POSTED_CHALLENGES = 'UNSET_POSTED_CHALLENGES';
export const SET_CHALLENGE_USER_API_STATUS = 'SET_CHALLENGE_USER_API_STATUS';
export const UNSET_CHALLENGE_USER_API_STATUS = 'UNSET_CHALLENGE_USER_API_STATUS';
export const RESET_SUCCESS_POST_COUNT = 'RESET_SUCCESS_POST_COUNT';
export const SET_UNSETTLED_CHALLENGES_INDEX = 'SET_UNSETTLED_CHALLENGES_INDEX';
export const SET_POSTED_CHALLENGE_PROGRESS = 'SET_POSTED_CHALLENGE_PROGRESS';
export const SET_CHALLENGE_USER_API_CANCEL_TOKEN = 'SET_CHALLENGE_USER_API_CANCEL_TOKEN';
export const CANCEL_POSTED_CHALLENGE = 'CANCEL_POSTED_CHALLENGE';
export const SET_POSTED_CHALLENGE_PROGRESS_COMPLETED = 'SET_POSTED_CHALLENGE_PROGRESS_COMPLETED';
export const LAST_POSTED_CHALLENGE = 'LAST_POSTED_CHALLENGE';

//set other userprofile
export const SET_OTHER_USER_CHALLENGES = 'SET_OTHER_USER_CHALLENGES';
export const UNSET_OTHER_USER_CHALLENGES = 'UNSET_OTHER_USER_CHALLENGES';
export const SET_OTHER_PROFILE_STATS = 'SET_OTHER_PROFILE_STATS';
export const SET_TIGMATE_REQUEST_STATUS = 'SET_TIGMATE_REQUEST_STATUS';
export const UPDATE_OTHER_USERPROFILE = 'UPDATE_OTHER_USERPROFILE';
export const SET_TIGMATE_REQUEST_NOTIFICATION_INDEX = 'SET_TIGMATE_REQUEST_NOTIFICATION_INDEX';
export const OTHER_USER_PROFILE_REQUESTED = 'OTHER_USER_PROFILE_REQUESTED';
export const REMOVE_OTHER_USER_PROFILE = 'REMOVE_OTHER_USER_PROFILE';
export const BLOCK_OTHER_USER_PROFILE = 'BLOCK_OTHER_USER_PROFILE';
export const UNBLOCK_OTHER_USER_PROFILE = 'UNBLOCK_OTHER_USER_PROFILE';
export const ADD_AS_TIGMATES = 'ADD_AS_TIGMATES';

//set,unset notifications
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const UNSET_NOTIFICATIONS = 'UNSET_NOTIFICATIONS';
export const POP_NOTIFICATION = 'POP_NOTIFICATION';
export const SET_NOTIFICATION_SEEN_STATUS = 'SET_NOTIFICATION_SEEN_STATUS';
export const SET_NOTIFICATION_SEEN_API_CALLED = 'SET_NOTIFICATION_SEEN_API_CALLED';
export const REFRESH_NOTIFICATIONS = 'REFRESH_NOTIFICATIONS';

//trending reducer
export const SET_TRENDING_API_STATUS = 'SET_TRENDING_API_STATUS';
export const UNSET_TRENDING_REDUCER = 'UNSET_TRENDING_REDUCER';

//Recommendation
export const SET_RECOMMENDATION_LIST = 'SET_RECOMMENDATION_LIST';
export const UNSET_RECOMMENDATION_LIST = 'UNSET_RECOMMENDATION_LIST';
export const SHOW_RECOMMENDATION_LIST = 'SHOW_RECOMMENDATION_LIST';

//Snackbar
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

export const SET_ACTIVE_PROFILE_TAB = 'SET_ACTIVE_PROFILE_TAB';
export const RESET_ACTIVE_PROFILE_TAB = 'RESET_ACTIVE_PROFILE_TAB';

export const SCROLL_TO_TOP = 'SCROLL_TO_TOP';
export const SHOW_FEEDBACK_FORM = 'SHOW_FEEDBACK_FORM';
export const SHOW_REVIEW_FORM = 'SHOW_REVIEW_FORM';

// failData
export const SET_FAIL_DATA = 'SET_FAIL_DATA';
