version: '4.0'
services:
  rabbitmq:
    container_name: rabbitmq_container_coffee
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=jobber
      - RABBITMQ_DEFAULT_PASS=jobberpass
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - elastic

  elasticsearch:
    container_name: elasticsearch_container_coffee
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    restart: always
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      network.host: 0.0.0.0
      transport.host: 127.0.0.1
      http.host: 0.0.0.0
      xpack.security.enabled: "true"
      xpack.security.authc.api_key.enabled: "true"
      xpack.monitoring.collection.enabled: "true"
      xpack.security.enrollment.enabled: "true"
      xpack.security.authc.token.enabled: "true"
      ELASTIC_PASSWORD: admin1234
    ports:
      - 9300:9300
      - 9200:9200
    volumes:
      - ./docker-volumes/elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    container_name: kibana_container_coffee
    image: docker.elastic.co/kibana/kibana:8.14.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch_container_coffee:9200"]
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana
      - ELASTICSEARCH_SERVICEACCOUNT_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL2NvZmZlZS1raWJhbmE6Qm9fVnl2d29Ud1dKN3hMdlhVa1g0UQ
      - XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS=["http://elasticsearch_container_coffee:9200"]
    ports:
      - 5601:5601
    networks:
      - elastic
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
  mysql:
    container_name: mysql_container_coffee
    image: mysql
    restart: always
    environment:
    - MYSQL_USER=jobber
    - MYSQL_DATABASE=jobber_auth_coffee
    - MYSQL_ROOT_PASSWORD=api
    - MYSQL_PASSWORD=api
    ports:
    - '3306:3306'
    volumes:
    - ./docker-volumes/mysql:/var/lib/mysql

  mongodb:
    container_name: mongodb_container_coffee
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker-volumes/data:/data/db

networks:
  elastic:
    name: elastic
